ReservEase/urls.py
from django.contrib import admin
from django.contrib.auth import urls
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('recursos/', include("recursos.urls")),
    path("accounts/", include("usuario.urls")),
    # path('accounts/', include(urls)),
    path("setor/", include("setor.urls")),
    path("reserva/", include("reserva.urls")),
    path("", include("recursos.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'usuario.views.hadler404'

setor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.listarSetores, name="listarsetores"), #padrão ir pra cá, padrão listar
    path("criarSetor/", views.criarSetor, name="criarSetor"),
    path("detalhar/<int:id_setor>", views.detalharSetor, name="detalharSetor"),
    path("alocarAdm/<int:id_setor>", views.alocarAdm, name="alocarAdm"),
    path("removerAdm/<int:id_adm>", views.removerAdm, name="removerAdm"),
    path("transferirAdm/<int:id_adm>", views.transferirAdm, name="transferirAdm"),
    path('editar/<int:id_setor>/', views.editarSetor, name='editarSetor'),
    path("deletar/<int:id_setor>", views.deletar, name="deletarSetor"),
    path("deletar/confirmar/<int:id_setor>", views.confirmarDelete, name="confirmarDeleteSetor"), 
]

recursos/models.py
from django.db import models
from setor.models import Setor
# Create your models here.

class Recurso(models.Model):
    nome = models.CharField(max_length=100, blank = False, null = False)
    imagem = models.ImageField(blank = False, null = False, upload_to='pictures/%Y/%m/')
    descricao = models.CharField(max_length=100, blank = True, null = True)

    class Meta: #a classe Recurso é abstrata e nao vai ter uma tabela para ela, apenas um modelo
        abstract = True
    
    #descobrir qual tipo de classe a instancia pertence 
    def get_tipo(self):
        return self.__class__.__name__

#herdando de recurso
class Equipamento(Recurso):
    quantTotal = models.IntegerField()
    setor = models.ForeignKey(Setor, on_delete=models.CASCADE, related_name="equipamentos")
    def __str__(self):
        return self.nome

class Espaco(Recurso):
    localizacao = models.CharField(max_length=100)
    setor = models.ForeignKey(Setor, on_delete=models.CASCADE, related_name="espacos")
    def __str__(self):
        return self.nome

setor/models.py
from django.db import models

class Setor(models.Model):
    nome = models.CharField(max_length=100, blank = 'False', null = 'False')
    def __str__(self):
        return self.nome

setor/forms.py
from typing import Any
from django import forms
from django.forms import ModelForm
from .models import Setor
from usuario.models import Usuario

class SetorForm(ModelForm):
    class Meta:
        model = Setor
        fields = [
            'nome'
        ]
        
class AlocarAdm(forms.Form):
    usuarios = forms.ModelMultipleChoiceField( #permite selecionar vários campos
        queryset=Usuario.objects.filter(setor__isnull=True, tipo=2),  # Filtra usuários sem setor atribuído
        widget=forms.CheckboxSelectMultiple,  # Exibe com caixas de seleção
        required=True  #obriga a selção de pelo menos uma caixa
    )

setor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import Error
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Setor
from usuario.models import Usuario
from recursos.models import Espaco, Equipamento
from .forms import SetorForm, AlocarAdm
from django.contrib.auth.models import Group
import os
from django.core.paginator import Paginator
from django.urls import reverse
from urllib.parse import urlencode
from django.contrib import messages

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def listarSetores(request):
    search_query = request.GET.get('searchbar', '') # pega o parâmetro de pesquisa
    setores_list = Setor.objects.all()
    if search_query:
        setores_list = setores_list.filter(
            nome__icontains=search_query
        )
    # paginação
    paginator = Paginator(setores_list, 10)  # mostra apenas 10 setores por página
    page_number = request.GET.get('page')
    setores = paginator.get_page(page_number)
    
    total_setores = setores_list.count()  # total de setores registrados
    
    return render(request, "partials/setor/listarSetores.html", {
        'setores': setores,
        'total_setores': total_setores,
        'search_query': search_query
    })

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def criarSetor(request):
    if request.method == 'POST':
        form = SetorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Setor criado com sucesso!")
            return HttpResponseRedirect('/setor/?msg=Salvo')
    else:
        form = SetorForm() #se tiver erro as informações do formulário voltam 
    return render(request, 'partials/setor/formSetor.html', {'form': form})

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def detalharSetor(request, id_setor):
    setor = Setor.objects.get(pk=id_setor)

    usuarios = setor.usuarios.all() # pega todos os usuarios que fazem parte do setor selecionado
    total_usuarios = len(usuarios)  # total de usuarios registrados no setor
    equipamentos = setor.equipamentos.all()  # Todos os equipamentos associados ao setor
    espacos = setor.espacos.all()  # Todos os espaços associados ao setor
    recursos = list(equipamentos) + list(espacos) #junta os espacos e equipamentos dentro de recursos
    total_recursos = len(recursos)  # total de recursos registrados no setor
    return render(request, "partials/setor/detalharSetor.html",{
        'setor': setor,
        'usuarios': usuarios,
        'total_usuarios': total_usuarios,
        'recursos': recursos,
        'total_recursos': total_recursos
    })

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def alocarAdm(request, id_setor):
    setor = Setor.objects.get(id=id_setor)

    if request.method == 'POST': #se receber um formulario
        form = AlocarAdm(request.POST) #armazena o que obteve pelo form
        if form.is_valid():
            usuarios = form.cleaned_data['usuarios'] #pega a lista dos usuarios selecionados
            for usuario in usuarios: #for para definir o atributo setor dos usuarios selecionados com o id do setor atual
                group, created = Group.objects.get_or_create(name='Administrador de Setor')  # Obtém ou cria o grupo
                usuario.groups.set([group])  # Define o grupo do usuário como o grupo 'Administrador de Setor' (remove qualquer outro que tinha antes)
                usuario.setor = setor
                usuario.save()
                messages.success(request, "Administrador de setor alocado com sucesso!")
            return redirect(reverse('detalharSetor', args=[id_setor])) # retorna para a pagina de detalhar o setor
    else:
        usuarios = Usuario.objects.filter(tipo=2) #filtra para usuarios do tipo 2
        form = AlocarAdm() #se tiver erro as informações do formulário voltam 

    return render(request, 'partials/setor/formAdmSetor.html', {'form': form, 'setor': setor})

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def removerAdm(request, id_adm):
    usuario = Usuario.objects.get(id=id_adm)

    id_setor = usuario.setor.id if usuario.setor else None   # busca que o setor está associado ao usuário

    group, created = Group.objects.get_or_create(name='Solicitante')  # Obtém ou cria o grupo
    usuario.groups.set([group])  # Define o grupo do usuário como o grupo 'Solicitante' (remove qualquer outro que tinha antes)
    usuario.setor = None
    usuario.save()

    url = reverse('detalharSetor', args=[id_setor]) 
    query_string = urlencode({'msg': 'salvo'})
    redirect_url = f'{url}?{query_string}'
    messages.success(request, "Administrador de setor removido com sucesso!")
    return redirect(redirect_url) #retorna a pagina anterior com o id setor


@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def transferirAdm(request, id_adm):
    usuario = Usuario.objects.get(id=id_adm) 
    idsetor= usuario.setor_id
    if request.method == 'POST':
        novo_setor_id = request.POST.get('setor')
        novo_setor = get_object_or_404(Setor, id=novo_setor_id)  # Obtém a instância do setor com base no ID
        usuario.setor = novo_setor  
        usuario.save()
        messages.success(request, "Administrador de setor transferido com sucesso!")
        return HttpResponseRedirect('/setor/?msg=Salvo')
    setores = Setor.objects.all()
    return render(request, 'partials/setor/formTransferirAdm.html', {'usuario': usuario, 'setores': setores, 'idsetor': idsetor})

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def editarSetor(request, id_setor):
    setor = Setor.objects.get(pk=id_setor)
    if request.method == 'POST':
        form = SetorForm(request.POST, instance= setor)
        if form.is_valid():
            form.save()
            messages.success(request, "Setor atualizado com sucesso!")
            return HttpResponseRedirect('/setor/?msg=Salvo')
    else:
        form = SetorForm(instance= setor)
    return render(request, 'partials/setor/editarSetor.html', {'form': form, 'id_setor': id_setor, 'setor': setor})

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm masterb
def confirmarDelete(request, id_setor):
    setor = Setor.objects.get(pk=id_setor)

    return render (request, 'partials/setor/confirmaExcluirSetor.html', {'setor':setor})

@user_passes_test(lambda u: u.groups.filter(name='Administrador Master').exists()) #só acessa se for adm master
def deletar(request, id_setor):
    Setor.objects.get(pk=id_setor).delete()
    messages.success(request, "Setor apagado com sucesso!")
    return HttpResponseRedirect("/setor/?msg=Exclui")

templates/partials/setor/confirmaExcluirSetor.html
{% extends 'partials/_base.html' %}

{% block content %}
{% load static %}
<head>
    <style>
        * {
            font-family: 'Poppins';
        }

        .btn {
            color: #fff;
            background-color: #A0BE3D;
            color: #fff;
            border: none;
            padding: 6px 30px;
            font-size: 12px;
            border-radius: 5px;
            text-decoration: none;
        }

        .btn-confirmar {
            background-color: #A0BE3D;
        }

        .btn-recusar {
            color: #fff;
            background-color: #e74c3c;
            border: 1px solid #e74c3c;
        }

        .btn-confirmar:hover {
            background-color: #48551B;
            border-color: #fff;
        }

        .btn-recusar:hover {
            background-color: #c0392b;
            border-color: #c0392b;
        }

        .btn-confirmacao {
            display: flex;
            gap: 30px;
        }

        img {
            width: 100%;
        }

        h3 {
            font-size: 20px;
        }

        .formEditar .imageRecurso {
            flex-direction: column;
            gap: 20px;
            width: 40%;
            display: flex;
            justify-content: center;
            align-items: center;

        }

        .container {
            margin-top: 40px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .identification-section {
            margin-top: 40px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            width: 95%;
            margin-left: 15px;
        }

        .identification-section #btnVoltar,
        .services-btns a {
            background-color: #022376;
            border: none;
            color: #fff;
            padding: 5px 12px;
            font-size: 12px;
            border-radius: 5px;
            text-decoration: none;
        }

        .identification-section #btnVoltar:hover {
            text-decoration: none;
            background-color: #010c29;
        }

        .title-service {
            font-size: 25px;
            
        }

        .subtitle-service {
            margin-top: 10px;
            font-size: 15px;
            margin-left: 15px;
        }
    </style>
</head>

<body>

    <div class="identification-section">
        <h1 class="title-service">Setores - {{setor.nome}} #{{ setor.id }}</h1>
        <a href="/setor/" id="btnVoltar">Voltar</a>
    </div>

    <div class="container">
        <h3 class="mt-3">Tem certeza que deseja excluir esse setor?</h3>
        <p>Essa ação excluirá os dados do setor cadastrado e não poderá ser desfeita.</p>

        <div class="formEditar">
                <p>Nome: {{ setor.nome }}</p>
        </div>

        <div class="btn-confirmacao">
            <a href="/setor/deletar/{{ setor.id }}" class="btn btn-confirmar">Sim</a>
            <a href="/setor/" class="btn btn-recusar">Não</a>
        </div>


    </div>

    <script src="{% static 'js/windowBack.js' %}"></script>
</body>
{% endblock %}

templates/partials/setor/editarSetor.html
{% extends 'partials/_base.html' %}

{% block content %}
{% load static %}
<style>
    * {
        font-family: 'Poppins';
    }

    .identification-section {
        margin-top: 40px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 95%;
        margin-left: 15px;
    }

    .identification-section #btnVoltar,
    .services-btns a {
        background-color: #022376;
        border: none;
        color: #fff;
        padding: 5px 12px;
        font-size: 12px;
        border-radius: 5px;
        text-decoration: none;
    }

    .identification-section #btnVoltar:hover {
        background-color: #010C29;
    }

    .title-service {
        font-size: 25px;
    }

    .subtitle-service {
        margin-top: 10px;
        font-size: 15px;
        margin-left: 15px;
    }

    div label {
        font-size: 14px;
        font-weight: 300;
        color: #333333;
    }

    div input {
        background-color: white;
        border: 0.1px solid #666666;
        border-radius: 5px;
        width: 100%;
        padding: 6px 5px;
        font-size: 13px;
    }

    form {
        display: flex;
        width: 90%;
        flex-direction: column;
        justify-content: center;
    }

    p {
        width: 50%;
        gap: 10px;
    }

    form .inputs-crud {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .container {
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .container a {
        font-size: 14px;
    }

    .container input[type="checkbox"] {
        width: 15px;
        height: 15px;
    }

    button[type="submit"] {
        background-color: #022376;
        border: none;
        color: #fff;
        padding: 6px 20px;
        font-size: 13px;
        border-radius: 5px;
        text-decoration: none;
    }

    button[type="submit"]:hover {
        background-color: #010C29;
    }

    form .button-container {
        width: 100%;
        display: flex;
        justify-content: center;
    }

    .section-form-sector {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>

{% load static %}
<section class="section-form-sector">
    <div class="identification-section">
        <h1 class="title-service">Setores - {{setor.nome}} #{{ setor.id }}</h1>
        <a href="/setor/" id="btnVoltar">Voltar</a>
    </div>

    <h2 class="subtitle-service">Dados gerais do recurso:</h2>

    <form action="/setor/editar/{{ id_setor }}/" method="post" enctype="multipart/form-data">
        <div class="inputs-crud">
            {% csrf_token %}
            {{ form.as_p }}
        </div>

        <div class="button-container">
            <button type="submit" class="btn btn-primary">Atualizar</button>
        </div>

    </form>

</section>
{% endblock %}

templates/partials/setor/formAdmSetor.html
{%  extends  "partials/_base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.icon' %}" type="image/x-icon">
    <title>Cadastrar Administrador | ReservEasy</title>
    <style>
        *{
            margin: 0;
            padding: 0;
            font-family: 'Poppins';
        }
        .form-register-admsector{
            margin: 50px;
            display: flex;
            flex-direction: column;
            gap: 20px;
            align-items: flex-start;
            
        }
        .identification-section{
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 100%;
        }
    .identification-section #btnVoltar, .services-btns a{
        background-color: #022376;
        border: none;
        color: #fff;
        padding: 5px 12px;
        font-size: 12px;
        border-radius: 5px;
        text-decoration: none;
    }
    .identification-section #btnVoltar:hover{
        text-decoration: none;
        background-color: #010C29;
    }
    .title-service{
    font-size:20px;  
    }
    .subtitle-service{
    font-size: 15px;
    font-weight: 500;
    }
    form{
    display: flex;
    flex-direction: column;
    width: 100%;
    align-items: center;
    }
    form .input-recurso{
    margin-left: 15px;
    width: 100%;
    display: flex;
    flex-wrap: wrap;
    margin-top: 30px;
    column-gap: 40px;
    align-items: center;
    justify-content: center;
    }
    form .input-recurso > p > #id_descricao{
    width: 840px;
    }
    form .button-container {
    width: 80%;
    display: flex;
    justify-content: center;
    margin-top: 20px;
    }
    .btn.submit:hover {
    background-color: #45a049;
    }
    .input-recurso p{
        display: flex;
        flex-direction: column;
        width: 70%;
        align-items: center;
    }

    .input-recurso p label {
        font-size:14px;
        color: #333333;
        font-weight: 400;
    }

    input[type="text"]{
    border: 0.1px solid #666666;
    border-radius: 5px;
    padding: 5px 5px;
    width: 80%;
    margin-top: 5px;
    }
    #btnCadastrar{
        background-color: #022376;
        border: none;
        color: #fff;
        padding: 5px 12px;
        font-size: 12px;
        border-radius: 5px;
        text-decoration: none;
    }
    #btnCadastrar:hover{
        text-decoration: none;
        background-color: #010C29;
    }
    .th-column {
        background-color: #E4E4E4 !important;
        color: #252525 !important;
        vertical-align: middle !important;
    }
    table {
        border-collapse: collapse;
        width: 50%;
        margin: 20px auto;
        text-align: center;
    }
    th, td {
        padding: 8px;
        font-size: 12px;
        text-align: center;
        vertical-align: middle !important;
    }
    th {
        background-color: #E4E4E4;
        color: black;
        font-size: 12px;
        width: 100%;
        display: flex;
        justify-content: center;
    }
    td {
        background-color: transparent !important;
        border: 0px solid #ccc !important;
        display: flex;
        width: 100%;
        justify-content: center;
    }
    tr{
        display: flex;
    }
    .th-column {
        background-color: #E4E4E4 !important;
        color: #252525 !important;
        vertical-align: middle !important;
    }
    table, thead, tr, th, tbody, td {
        border: 0 !important;
        text-align: start;
    }
    td, .th-column {
        padding: 5px !important;
    }
    th {
        padding-left: 5px !important;
        padding-right: 5px !important;
    }
    table, thead, tr, th, tbody, td {
        border: 0 !important;
        text-align: start;
    }
    td, .th-column {
        padding: 5px !important;
    }
    th {
        padding-left: 5px !important;
        padding-right: 5px !important;
    }
    .tr-row, tr {
        border-bottom: 1px solid #ccc !important;
        
    }
    .th-column{
        background-color: transparent !important;
        border: 0px solid #ccc;
    }
     .search-container {
            margin-bottom: 20px;
            width: 100%;
            text-align: center;
        }
        .search-container input {
            width: 80%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 14px;
        }
    </style>
    <script src="https://kit.fontawesome.com/88a7a49c60.js" crossorigin="anonymous"></script>

</head>
<body>
    <section class="form-register-admsector">
        <div class="identification-section">
            <h1 class="title-service"> Administradores - {{ setor.nome}}</h1>
            <a href="/setor/detalhar/{{ setor.id}}" id="btnVoltar" >Voltar</a>
        </div>
        <h2 class="subtitle-service">Selecione os usuários que você deseja designar como administradores do setor:</h2>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="input-recurso">
                {% csrf_token %}
                <div class="search-container">
                    <input type="text" id="searchInput" placeholder="Buscar usuários...">
                </div>

                <table id="userTable">
                    <thead>
                        <tr>
                            <th>Selecionar</th>
                            <th>Usuário</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for widget in form.usuarios %}
                            <tr>
                                <td>{{ widget.tag }}</td>
                                <td>{{ widget.choice_label }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="2">Nenhum usuário encontrado.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        document.getElementById('searchInput').addEventListener('input', function() {
                            const searchText = this.value.toLowerCase();
                            const rows = document.querySelectorAll('#userTable tbody tr');

                            rows.forEach((row) => {
                                const cells = row.querySelectorAll('td');
                                const match = Array.from(cells).some(cell => cell.textContent.toLowerCase().includes(searchText));

                                if (match) {
                                    row.style.display = '';
                                } else {
                                    row.style.display = 'none';
                                }
                            });
                        });
                    });
                </script>
            </div>
            <div class="button-container">
                <button type="submit" id="btnCadastrar">Cadastrar</button>
            </div>
        </form>
    </section>

</body>
</html>
{% endblock%}

templates/partials/setor/formSetor.html
{% extends 'partials/_base.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <link rel="stylesheet" href="{% static 'css/formSetor.css'%}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="shortcut icon" href="{% static 'favicon.icon' %}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/88a7a49c60.js" crossorigin="anonymous"></script>
</head>

<body>
    <section class="section-form-sector">
        <div class="identication-service-instrucion">
            <div class="identification-section">
                <h1 class="title-service">Setores - Cadastramento de Setor</h1>
                <a href="/setor/" id="btnVoltar">Voltar</a>
            </div>
            <h2 class="subtitle-service">Insira os dados gerais do novo setor</h2>
        </div>
        <div class="layoutFlex">
            <div class="widget-symbol" id="image-preview"><i class="fa-solid fa-box-archive"></i></div>
            <form action="" method="post">

                <div class="input-recurso">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="button-container">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>
            </form>
        </div>
    </section>
    <script src="{% static 'js/inputs.js '%}"></script>
    <script src="{% static 'js/windowBack.js' %}"></script>

</body>

</html>
{% endblock %}

templates/partials/setor/formTransferirAdm.html
{%  extends  "partials/_base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transferir Administrador | ReservEasy</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'favicon.icon' %}" type="image/x-icon">
    <style>
        .form-register-admsector{
            margin: 50px;
            display: flex;
            flex-direction: column;
            gap: 40px;
            align-items: flex-start;
        }
        .identification-section{
            display: flex;
            align-items: center;
            justify-content: space-between;
            width: 100%;
            }
        .identification-section #btnVoltar, .services-btns a{
            background-color: #022376;
            border: none;
            color: #fff;
            padding: 5px 12px;
            font-size: 12px;
            border-radius: 5px;
            text-decoration: none;
        }
        .identification-section #btnVoltar:hover{
            text-decoration: none;
            background-color: #010C29;
        }
        .title-service{
        font-size:20px;  
        }
        .subtitle-service{
        font-size: 15px;
        font-weight: 500;
        }
        form{
        display: flex;
        flex-direction: column;
        width: 100%;
        align-items: center;
        }
        form .input-recurso{
        margin-left: 15px;
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        margin-top: 30px;
        column-gap: 40px;
        align-items: center;
        justify-content: center;
        }
        form .button-container {
            width: 80%;
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }
        #btnCadastrar{
            background-color: #022376;
            border: none;
            color: #fff;
            padding: 5px 12px;
            font-size: 12px;
            border-radius: 5px;
            text-decoration: none;
        }
        #btnCadastrar:hover{
            text-decoration: none;
            background-color: #010C29;
        }
    </style>
</head>
<body>
    <section class="form-register-admsector">
        <div class="identification-section">
            <h1 class="title-service"> Administradores - Transferência de Setor</h1>
            <a href="/setor/detalhar/{{ idsetor }}" id="btnVoltar" >Voltar</a>
        </div>
        <h2 class="subtitle-service">Você está transferindo o administrador <strong>{{ usuario.first_name }} {{ usuario.last_name }}</strong>, de id <strong> {{usuario.id}} </strong>, atualmente alocado no setor <strong> {{usuario.setor}} </strong>, para um novo setor.</h2>
        <form action="" method="post">
            <div class="input-recurso">
                {% csrf_token %}
                <label for="setor">Selecione o Novo Setor:</label>
                <select id="setor" name="setor" class="form-control" required>
                    {% for setor in setores %}
                        <option value="{{ setor.id }}">{{ setor.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="button-container">
                <button type="submit" id="btnCadastrar">Transferir</button>
            </div>
        </form>
    </section>
    <script src="{% static 'js/windowBack.js '%}"></script>
</body>
</html>
{% endblock%}